# Generated by Django 6.0.3 on 2026-03-28 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AILessonSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.PositiveIntegerField(unique=True, verbose_name='Dars ID')),
                ('lesson_title', models.CharField(max_length=255, verbose_name='Dars sarlavhasi')),
                ('summary', models.TextField(verbose_name='AI xulosasi')),
                ('key_terms', models.TextField(blank=True, help_text='JSON formatida: ["atama1", "atama2"]', verbose_name='Asosiy atamalar (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dars AI xulosasi',
                'verbose_name_plural': 'Dars AI xulosalari',
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dars ID')),
                ('lesson_title', models.CharField(blank=True, max_length=255, verbose_name='Dars sarlavhasi (kontekst)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'AI suhbat',
                'verbose_name_plural': 'AI suhbatlar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIEssayCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(verbose_name='Asl matn')),
                ('feedback', models.TextField(blank=True, verbose_name='AI tahlili')),
                ('grammar_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Grammatika bali (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_checks', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Insho tekshiruvi',
                'verbose_name_plural': 'Insho tekshiruvlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('assistant', 'AI')], max_length=10, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Matn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_modules.aiconversation', verbose_name='Suhbat')),
            ],
            options={
                'verbose_name': 'AI xabar',
                'verbose_name_plural': 'AI xabarlar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_lesson_ids', models.TextField(default='[]', verbose_name='Tavsiya etilgan darslar (JSON)')),
                ('reasoning', models.TextField(blank=True, verbose_name='Sabab')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'AI tavsiya',
                'verbose_name_plural': 'AI tavsiyalar',
            },
        ),
    ]
