# Generated by Django 6.0.3 on 2026-03-28 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('lessons_5', "5 ta dars ko'rildi"), ('lessons_20', "20 ta dars ko'rildi"), ('lessons_50', "50 ta dars ko'rildi"), ('first_test', 'Birinchi test topshirildi'), ('first_certificate', 'Birinchi sertifikat'), ('perfect_score', '100% ball (mukammal natija)'), ('streak_7', '7 kun ketma-ket'), ('all_subjects', "Barcha fanlardan test o'tildi")], max_length=20, unique=True, verbose_name='Badge turi')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('description', models.CharField(max_length=300, verbose_name='Tavsifi')),
                ('icon', models.CharField(default='bi-award', max_length=50, verbose_name='Bootstrap Icons class')),
                ('color', models.CharField(default='#1A6FD4', max_length=7, verbose_name='Rang (hex)')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badgelar',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Olingan sana')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='leaderboard.badge', verbose_name='Badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi badgesi',
                'verbose_name_plural': 'Foydalanuvchi badgelari',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
