# Generated by Django 6.0.3 on 2026-04-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_count', models.CharField(default='0', help_text='Masalan: 10,000+', max_length=50, verbose_name="O'quvchilar soni")),
                ('video_lessons_count', models.CharField(default='0', help_text='Masalan: 800+', max_length=50, verbose_name='Video darslar soni')),
                ('subjects_count', models.CharField(default='0', help_text='Masalan: 15+', max_length=50, verbose_name='Fanlar soni')),
                ('certificates_count', models.CharField(default='0', help_text='Masalan: 4,200+', max_length=50, verbose_name='Sertifikatlar soni')),
                ('active_students_count', models.CharField(default='0', help_text='Masalan: 10K+', max_length=50, verbose_name="Faol o'quvchilar")),
                ('average_rating', models.CharField(default='4.9', help_text='Masalan: 4.9', max_length=20, verbose_name="O'rtacha baho")),
                ('test_questions_count', models.CharField(default='0', help_text='Masalan: 1,200+', max_length=50, verbose_name='Test savollari soni')),
                ('grades_count', models.CharField(default='11', help_text='Masalan: 11', max_length=20, verbose_name='Sinf darslari soni')),
                ('use_real_stats', models.BooleanField(default=False, help_text="Yoqilganda bazadagi haqiqiy raqamlar ko'rsatiladi", verbose_name='Haqiqiy statistikani ishlatish')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
