# Generated by Django 6.0.3 on 2026-03-28 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', "Ko'p tanlovli (A/B/C/D)"), ('tf', "To'g'ri / Noto'g'ri"), ('image', 'Rasm bilan savol')], default='mcq', max_length=5, verbose_name='Savol turi')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Rasm')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('score', models.PositiveSmallIntegerField(default=1, verbose_name='Ball')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Variant matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Test sarlavhasi')),
                ('quiz_type', models.CharField(choices=[('lesson', 'Dars testi'), ('quarter', 'Chorak testi')], max_length=10, verbose_name='Test turi')),
                ('time_limit', models.PositiveSmallIntegerField(default=0, help_text="0 = vaqt chegarasi yo'q", verbose_name='Vaqt chegarasi (daqiqa)')),
                ('pass_score', models.PositiveSmallIntegerField(default=80, verbose_name="O'tish bali (%)")),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='lessons.lesson', verbose_name='Dars')),
                ('quarter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='lessons.quarter', verbose_name='Chorak')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ball (%)')),
                ('correct_count', models.PositiveSmallIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('total_questions', models.PositiveSmallIntegerField(default=0, verbose_name='Jami savollar')),
                ('is_passed', models.BooleanField(default=False, verbose_name="O'tildi")),
                ('is_completed', models.BooleanField(default=False, verbose_name='Yakunlandi')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Test urinishi',
                'verbose_name_plural': 'Test urinishlari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in', to='quizzes.choice', verbose_name='Tanlangan variant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='quizzes.question', verbose_name='Savol')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt', verbose_name='Urinish')),
            ],
            options={
                'verbose_name': 'Test javobi',
                'verbose_name_plural': 'Test javoblari',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
