# Generated by Django 6.0.3 on 2026-04-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=3, help_text='Necha marta test ishlash mumkin (0 = cheksiz)', verbose_name='Maksimal urinishlar soni'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pass_score',
            field=models.PositiveSmallIntegerField(default=70, verbose_name="O'tish bali (%)"),
        ),
    ]
