# Generated by Django 6.0.3 on 2026-03-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fan nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('color', models.CharField(choices=[('blue', "Ko'k"), ('red', 'Qizil'), ('green', 'Yashil')], default='blue', max_length=10, verbose_name='Rang')),
                ('icon', models.CharField(default='bi-book', help_text='Masalan: bi-calculator, bi-globe', max_length=50, verbose_name='Bootstrap Icons class')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['order', 'name'],
            },
        ),
    ]
