# Generated by Django 6.0.3 on 2026-03-28 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_lesson', 'Yangi dars'), ('test_result', 'Test natijasi'), ('certificate', 'Sertifikat'), ('system', 'Tizim xabari')], max_length=15, verbose_name='Tur')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qildi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_lesson_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_quiz_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_certificate_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=300, verbose_name='Havola')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
