# Generated by Django 6.0.3 on 2026-03-28 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, '1-sinf'), (2, '2-sinf'), (3, '3-sinf'), (4, '4-sinf'), (5, '5-sinf'), (6, '6-sinf'), (7, '7-sinf'), (8, '8-sinf'), (9, '9-sinf'), (10, '10-sinf'), (11, '11-sinf')], verbose_name='Sinf')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, '1-chorak'), (2, '2-chorak'), (3, '3-chorak'), (4, '4-chorak')], verbose_name='Chorak')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='subjects.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Chorak',
                'verbose_name_plural': 'Choraklar',
                'ordering': ['grade', 'subject', 'number'],
                'unique_together': {('subject', 'grade', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, '1-sinf'), (2, '2-sinf'), (3, '3-sinf'), (4, '4-sinf'), (5, '5-sinf'), (6, '6-sinf'), (7, '7-sinf'), (8, '8-sinf'), (9, '9-sinf'), (10, '10-sinf'), (11, '11-sinf')], verbose_name='Sinf')),
                ('title', models.CharField(max_length=255, verbose_name='Dars sarlavhasi')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('video_provider', models.CharField(choices=[('cloudflare', 'Cloudflare Stream'), ('vimeo', 'Vimeo')], default='cloudflare', max_length=15, verbose_name='Video provider')),
                ('pdf_conspect', models.FileField(blank=True, null=True, upload_to='conspects/', verbose_name='PDF konspekt')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='lesson_thumbnails/', verbose_name='Muqova rasmi')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Davomiyligi (daqiqa)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='subjects.subject', verbose_name='Fan')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.quarter', verbose_name='Chorak')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False, verbose_name="To'liq ko'rildi")),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='lessons.lesson', verbose_name='Dars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_views', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Dars ko'rish",
                'verbose_name_plural': "Dars ko'rishlar",
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
