# Generated by Django 6.0.3 on 2026-04-12 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_add_video_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='quarter',
            name='is_premium',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_provider',
            field=models.CharField(choices=[('cloudflare', 'Cloudflare Stream'), ('vimeo', 'Vimeo'), ('local', 'Lokal fayl')], default='cloudflare', max_length=15, verbose_name='Video provider'),
        ),
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Izoh matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lessons.lesson', verbose_name='Dars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_comments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Dars izohi',
                'verbose_name_plural': 'Dars izohlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
