# Generated by Django 6.0.3 on 2026-04-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_lesson_is_premium_remove_quarter_is_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (masalan: https://youtube.com/watch?v=XXXXXXXXXXX yoki https://youtu.be/XXXXXXXXXXX)', verbose_name='YouTube video havolasi'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/', verbose_name='Eski video fayl (ishlatilmaydi)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_provider',
            field=models.CharField(blank=True, default='youtube', max_length=15, verbose_name='Video manbai'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Eski video URL (ishlatilmaydi)'),
        ),
    ]
